spring:
  profiles:
    active: dev
  application:
    name: med-app
  security:
    secret-key: NTUyODc4MDA0Mzc2MTE0NzQwMzE1NjczNjcyMzgxMTcwMDIyNDExNjc2NzY0NDg0MTI4MTU1Mzc2NzMxNDg3Nw==


  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    host: localhost
    port: 1025

server:
  port: 8080

